version: '3'

services:
  mongo-db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin1234
      MONGO_INITDB_DATABASE: uptask_db
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
